---
title: "tidymodel official get started chpt 4 Tune model parameters"
author: "류성균"
date: '2020 12 26 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- reference : https://www.tidymodels.org/start/tuning/

```{r}
library(tidymodels)  # for the tune package, along with the rest of tidymodels

# Helper packages
library(modeldata)   # for the cells data
library(vip)         # for variable importance plots
```

### The cell image data, revisited

```{r}
data(cells, packages = "modeldata")

glimpse(cells)
```

### Predicting image segmentation, but better

```{r}
set.seed(123)
cell_split <- initial_split(cells %>% select(-case), 
                            starta = class)

cell_train <- training(cell_split)
cell_test <- testing(cell_split)
```

### Tuning hyperparameters
```{r}
tune_spec <-
  decision_tree(
    cost_complexity = tune(),
    tree_depth = tune()
  ) %>% 
  set_engine("rpart") %>% 
  set_mode("classification")

tune_spec
```

```{r}
### grid_regular from dials package
tree_grid <- grid_regular(cost_complexity(),
                          tree_depth(),
                          levels = 5) # parameter별로 5개씩 테스트, 총 25개
```

```{r}
tree_grid
```

```{r}
tree_grid %>% 
  count(tree_depth)
```

```{r}
tree_grid %>% 
  count(cost_complexity)
```

```{r}
set.seed(234)
cell_folds <- vfold_cv(cell_train)
```

### Model tunning with a grid

```{r}
set.seed(345)

tree_wf <- workflow() %>% 
  add_model(tune_spec) %>% 
  add_formula(class ~ .) # add_recipe로 대체 가능능

tree_res <-
  tree_wf %>% 
  tune_grid(
    resamples = cell_folds,
    grid = tree_grid
  )

tree_res
```

```{r}
tree_res %>% 
  collect_metrics()

```

```{r}
tree_res %>% 
  collect_metrics() %>% 
  mutate(tree_depth = factor(tree_depth)) %>% 
  ggplot(aes(cost_complexity, mean, color = tree_depth)) +
  geom_line(size = 1.5, alpha = 0.6) +
  geom_point(size = 2) +
  facet_wrap(~ .metric, scales = "free", nrow = 2) + 
  scale_x_log10(labels = scales::label_number()) + 
  scale_color_viridis_d(option = "plasma", begin = 0.9, end = 0)
```

```{r}
tree_res %>% 
  show_best("roc_auc")
```

```{r}
best_tree <- tree_res %>% 
  select_best("roc_auc")

best_tree
```

### Finalizing our model

```{r}
final_wf <-
  tree_wf %>% 
  finalize_workflow(best_tree)

final_wf
```

### Exploring result
```{r}
final_tree <-
  final_wf %>% 
  fit(data = cell_train)

final_tree
```

```{r}
final_tree %>% 
  pull_workflow_fit() %>% 
  vip()
```

### The last fit ? 

- last_fit과 fit의 차이는 뭐지?

```{r}
final_fit <-
  final_wf %>% 
  last_fit(cell_split)

final_fit %>% 
  collect_metrics()
```

```{r}
final_fit %>% 
  collect_predictions() %>% 
  roc_curve(class, .pred_PS) %>% 
  autoplot()
```

- tuning할 수 있는 parameter 확인
```{r}
args(decision_tree)
```

